#!/usr/bin/env node
// Tests for vercel.json rewrite pattern generated by _executePublish.
//
// Run: node tests/vercel-rewrite.spec.cjs

const assert = require("node:assert");

const results = [];

function log(status, name, detail) {
  const icon = status === "PASS" ? "\u2713" : "\u2717";
  console.log(`  ${icon} ${name}${detail ? " \u2014 " + detail : ""}`);
  results.push({ status, name });
}

// The rewrite pattern from src/main.js _executePublish (private deploys).
// Vercel uses path-to-regexp which anchors the pattern to the full path,
// so we anchor with ^ and $ to replicate Vercel's matching behavior.
const REWRITE_SOURCE = "/((?!api/).*)";
const rewriteRe = new RegExp("^" + REWRITE_SOURCE + "$");

console.log("\nVercel Rewrite Pattern Tests\n");

// ── Test 1: atpath/ paths match the rewrite (are NOT excluded) ────────
try {
  assert.ok(rewriteRe.test("/atpath/style.css"), "atpath/style.css matches rewrite");
  assert.ok(rewriteRe.test("/atpath/some-page"), "atpath/some-page matches rewrite");
  assert.ok(rewriteRe.test("/atpath/sub/dir/file.js"), "atpath nested path matches rewrite");
  log("PASS", "atpath/ paths match the rewrite (not excluded)");
} catch (e) {
  log("FAIL", "atpath/ paths match the rewrite (not excluded)", e.message);
}

// ── Test 2: api/ paths are excluded from the rewrite ──────────────────
try {
  assert.ok(!rewriteRe.test("/api/auth"), "api/auth excluded from rewrite");
  assert.ok(!rewriteRe.test("/api/approve"), "api/approve excluded from rewrite");
  log("PASS", "api/ paths are excluded from the rewrite");
} catch (e) {
  log("FAIL", "api/ paths are excluded from the rewrite", e.message);
}

// ── Test 3: Root and regular paths match the rewrite ──────────────────
try {
  assert.ok(rewriteRe.test("/"), "Root path matches rewrite");
  assert.ok(rewriteRe.test("/some-page"), "Regular page matches rewrite");
  assert.ok(rewriteRe.test("/deep/nested/path"), "Deep nested path matches rewrite");
  log("PASS", "Root and regular paths match the rewrite");
} catch (e) {
  log("FAIL", "Root and regular paths match the rewrite", e.message);
}

// ── Test 4: Pattern matches what src/main.js actually generates ───────
try {
  const fs = require("node:fs");
  const src = fs.readFileSync(require("path").join(__dirname, "..", "src", "main.js"), "utf-8");

  assert.ok(
    src.includes('"/((?!api/).*)"'),
    "src/main.js contains the expected rewrite pattern"
  );
  // The rewrite source string itself must not contain "atpath/"
  const rewriteLine = src.match(/"\/\(.*?\)"/g) || [];
  const hasAtpathExclusion = rewriteLine.some(p => p.includes("atpath"));
  assert.ok(
    !hasAtpathExclusion,
    "Rewrite pattern does not exclude atpath/"
  );

  log("PASS", "Pattern in src/main.js matches expected value");
} catch (e) {
  log("FAIL", "Pattern in src/main.js matches expected value", e.message);
}

// ── Summary ───────────────────────────────────────────────────────────
const failed = results.filter((r) => r.status === "FAIL").length;
console.log("\n" + results.length + " tests, " + failed + " failed\n");
process.exit(failed > 0 ? 1 : 0);
